### ISSUE TITLE
Issue getFullYear is not a function

### ISSUE THREAD

**Issue by mdupree** [cymen/react-daypicker#9]
DayPicker.js:209 Uncaught TypeError: e.getFullYear is not a function

Getting this error when trying to use daypicker like so.
` <DayPicker
                active={moment().add(1, 'day')}
                onDayClick={(day) => this.setState({ day })}
              />`

If I remove active prop it works but doesn't show which day is selected

**Comment by cymen** [comment]
@mdupree Somehow I missed this but I think this is likely down to this component no longer expecting a moment-wrapped date but instead a vanilla Date object (which does support `getFullYear`).
